# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@hmpps-book-secure-move-frameworks*'
      - dependency-name: 'webpack-cli'
        versions: ['>=4']
      - dependency-name: 'webpack-merge'
        versions: ['>=5']
      - dependency-name: 'convert-hrtime'
        versions: ['>=4']
    commit-message:
      prefix: 'build'
      include: 'scope'
    open-pull-requests-limit: 10
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      - dependency-name: 'node'
        versions: ['>=15']
    open-pull-requests-limit: 1
