name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable or testing tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  packages: write
  actions: write

concurrency:
  # Only cancel in progress when on a branch - use SHA on main to ensure uniqueness.
  # This will allow multiple pipelines to run at the same time on main.
  # Note that two pipelines running within a few minutes of each other will cause issues with helm deploying to
  # a namespace, as the second one will not be able to get a lock as a deploy will be in progress.
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # main node build workflow
  node_build:
    name: Run the node build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: Install image optimisation libs
        shell: bash
        run: |
          yarn add pngquant optipng
      - name: Install npm dependencies
        shell: bash
        run: |
          npm install -g npm@11 && npm install && npm rebuild node-sass
      - name: install dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        shell: bash
        run: ""
      - name: build npm
        shell: bash
        run: |
          npm run build
      - name: upload the artifacts
        uses: actions/upload-artifact@v6
        with:
          name: npm_build_artifacts
          include-hidden-files: true
          path: |
            .build/
      - name: save cache
        id: save-cache
        uses: actions/cache/save@v5
        env:
          cache-name: node-modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: list files
        shell: bash
        run: |
          ls -la
  # generic node unit tests - feel free to override with local tests if required
  lint:
    name: Run eslint
    runs-on: ubuntu-latest
    needs: [node_build]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: npm_build_artifacts
          path: ".build"
      - name: install
        shell: bash
        run: |
          npm install -g npm@11 && npm install
      - name: Write eslintignore
        shell: bash
        run: |
          npx tsc --listFilesOnly | grep -v 'node_modules' | sed 's/\.ts/\.js/' | sed "s#$(pwd)/##" > ./.eslintignore
      - name: Run linter
        shell: bash
        run: |
          npm run ci:lint
  # generic node unit tests - feel free to override with local tests if required
  unit_test:
    name: Run the unit tests
    runs-on: ubuntu-latest
    needs: [node_build, lint]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env:
          cache-name: node-modules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json', '!**/node_modules/**') }}
      - name: download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: npm_build_artifacts
          path: ".build"
      - name: install
        shell: bash
        run: |
          npm install -g npm@11 && npm install
      - name: Run tests
        shell: bash
        run: |
          npm run test

  node_integration_tests:
    name: node integration tests
    uses: ./.github/workflows/integration_tests.yml
    needs: [node_build, lint, unit_test]
    secrets: inherit
    with:
      app_version: ${{ needs.build_docker.outputs.app_version }}
  helm_lint:
    strategy:
      matrix:
        environments: ['dev', 'uat', 'preprod', 'production']
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}
  build:
    name: Build docker image from hmpps-github-actions
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    needs:
      - node_integration_tests
      - unit_test
    with:
      docker_registry: 'ghcr.io'
      registry_org: 'ministryofjustice'
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false
  deploy_staging:
    name: Deploy to the staging environment
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'staging'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_uat:
    name: Deploy to the UAT environment
    needs:
      - build
      - deploy_staging
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'uat'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - build
      - deploy_staging
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'
  deploy_prod:
    name: Deploy to production environment
    needs:
      - build
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'production'
      app_version: '${{ needs.build.outputs.app_version }}'
